import type {
  Service,
  Port,
  Secret,
  Alert,
  ResourceLink,
  User,
  ConfigPolicy,
  AuditEntry,
  HealthMatrixEntry,
  Incident,
  DashboardStats,
  ResourceSnapshot,
  MonitoringMetrics,
  MetricPoint,
} from '../types';

function makeMetrics(): MonitoringMetrics {
  const now = Date.now();
  const points = (count: number, base: number, variance: number) => {
    const arr: MetricPoint[] = [];
    for (let i = 0; i < count; i++) {
      const t = now - (count - i) * 5 * 60 * 1000;
      arr.push({ timestamp: new Date(t).toISOString(), value: base + variance * Math.sin(i / 6) + (Math.random() - 0.5) * variance * 0.4 });
    }
    return arr;
  };
  return {
    cpu: points(24, 35, 8),
    memory: points(24, 62, 4),
    disk: points(24, 48, 1),
    networkIn: points(24, 120_000_000, 30_000_000),
    networkOut: points(24, 80_000_000, 20_000_000),
    requestRate: points(24, 4200, 800),
    errorRate: points(24, 0.4, 0.2),
    activeSessions: points(24, 180, 40),
  };
}

export const currentSnapshot: ResourceSnapshot = {
  cpuPercent: 41,
  memoryPercent: 64,
  memoryBytes: 4_210_000_000,
  diskPercent: 48,
  diskBytes: 192_000_000_000,
  networkIn: 142_000_000,
  networkOut: 92_000_000,
  requestRate: 4_620,
  errorRate: 0.42,
  activeSessions: 188,
};

export const metrics = makeMetrics();

export const services: Service[] = [
  {
    id: 'dograh-api',
    name: 'Capstone Voice API',
    description: 'Telephony orchestration API powering VoIP agent routing, ARI bindings, and extension management.',
    version: '1.45.1',
    status: 'healthy',
    healthScore: 98,
    cpuUsage: 32,
    memoryUsage: 48,
    memoryBytes: 1_200_000_000,
    trafficBytesPerSec: 45_000_000,
    lastRestart: '2026-08-29T14:12:00Z',
    uptimeSeconds: 6_824_400,
    environment: 'prod',
    owner: 'DevOps',
    tags: ['voice', 'telephony', 'core'],
    health: {
      checkedAt: new Date().toISOString(),
      latencyMs: 18,
      errorRate: 0.2,
      availability: 99.97,
      status: 'healthy',
      dependencies: ['postgres', 'redis'],
    },
  },
  {
    id: 'dograh-ui',
    name: 'Capstone Voice App',
    description: 'Web dashboard for agent workflow authoring, telephony configuration, and extension bindings.',
    version: '2.9.0',
    status: 'healthy',
    healthScore: 96,
    cpuUsage: 21,
    memoryUsage: 62,
    memoryBytes: 900_000_000,
    trafficBytesPerSec: 18_000_000,
    lastRestart: '2026-08-30T09:05:00Z',
    uptimeSeconds: 1_209_600,
    environment: 'prod',
    owner: 'Frontend',
    tags: ['ui', 'agent-workflows'],
    health: {
      checkedAt: new Date().toISOString(),
      latencyMs: 24,
      errorRate: 0.5,
      availability: 99.95,
      status: 'healthy',
      dependencies: ['dograh-api'],
    },
  },
  {
    id: 'freepbx',
    name: 'FreePBX',
    description: 'Asterisk/FreePBX PBX hosting SIP registrations, dialplan, and inbound route mappings for Capstone agents.',
    version: '16.0.26',
    status: 'warning',
    healthScore: 82,
    cpuUsage: 58,
    memoryUsage: 73,
    memoryBytes: 1_800_000_000,
    trafficBytesPerSec: 38_000_000,
    lastRestart: '2026-08-28T22:40:00Z',
    uptimeSeconds: 9_331_200,
    environment: 'prod',
    owner: 'PBX Ops',
    tags: ['pbx', 'asterisk', 'sip'],
    health: {
      checkedAt: new Date().toISOString(),
      latencyMs: 42,
      errorRate: 1.1,
      availability: 99.89,
      status: 'warning',
      dependencies: ['dograh-api'],
    },
  },
  {
    id: 'omniroute',
    name: 'OmniRoute',
    description: 'L7 LLM gateway multiplexing cloud and on-prem providers with rate limiting, caching, and billing accounting.',
    version: '1.12.4',
    status: 'healthy',
    healthScore: 99,
    cpuUsage: 14,
    memoryUsage: 41,
    memoryBytes: 650_000_000,
    trafficBytesPerSec: 92_000_000,
    lastRestart: '2026-08-30T06:00:00Z',
    uptimeSeconds: 1_468_800,
    environment: 'prod',
    owner: 'Platform',
    tags: ['llm', 'gateway', 'routing'],
    health: {
      checkedAt: new Date().toISOString(),
      latencyMs: 11,
      errorRate: 0.1,
      availability: 99.99,
      status: 'healthy',
      dependencies: [],
    },
  },
  {
    id: 'n8n',
    name: 'n8n Workflow',
    description: 'Automation orchestrator running interview grader webhooks, transcript fetch, and Grist document writes.',
    version: '2.2.0',
    status: 'healthy',
    healthScore: 95,
    cpuUsage: 19,
    memoryUsage: 55,
    memoryBytes: 780_000_000,
    trafficBytesPerSec: 6_000_000,
    lastRestart: '2026-08-30T07:30:00Z',
    uptimeSeconds: 1_360_800,
    environment: 'prod',
    owner: 'Automation',
    tags: ['automation', 'webhooks'],
    health: {
      checkedAt: new Date().toISOString(),
      latencyMs: 31,
      errorRate: 0.3,
      availability: 99.93,
      status: 'healthy',
      dependencies: ['grist', 'dograh-api'],
    },
  },
  {
    id: 'grist',
    name: 'Grist Interviews',
    description: 'Structured interview records, candidate loops, and call metadata store for grading workflows.',
    version: '1.7.0',
    status: 'healthy',
    healthScore: 97,
    cpuUsage: 11,
    memoryUsage: 38,
    memoryBytes: 520_000_000,
    trafficBytesPerSec: 3_000_000,
    lastRestart: '2026-08-30T07:00:00Z',
    uptimeSeconds: 1_396_800,
    environment: 'prod',
    owner: 'Data',
    tags: ['data', 'interviews'],
    health: {
      checkedAt: new Date().toISOString(),
      latencyMs: 9,
      errorRate: 0.1,
      availability: 99.98,
      status: 'healthy',
      dependencies: [],
    },
  },
  {
    id: 'signoz',
    name: 'SigNoz Observability',
    description: 'OpenTelemetry traces, metrics, and logs backend providing service-level dashboards and alerting.',
    version: '1.4.1',
    status: 'healthy',
    healthScore: 94,
    cpuUsage: 43,
    memoryUsage: 71,
    memoryBytes: 2_100_000_000,
    trafficBytesPerSec: 12_000_000,
    lastRestart: '2026-08-29T18:00:00Z',
    uptimeSeconds: 5_760_000,
    environment: 'prod',
    owner: 'SRE',
    tags: ['observability', 'traces', 'logs'],
    health: {
      checkedAt: new Date().toISOString(),
      latencyMs: 36,
      errorRate: 0.2,
      availability: 99.96,
      status: 'healthy',
      dependencies: ['clickhouse'],
    },
  },
  {
    id: 'clickhouse',
    name: 'ClickHouse',
    description: 'OLAP storage for telemetry streams, latency percentiles, and long-term metric retention.',
    version: '24.8.0',
    status: 'healthy',
    healthScore: 97,
    cpuUsage: 28,
    memoryUsage: 68,
    memoryBytes: 3_200_000_000,
    trafficBytesPerSec: 64_000_000,
    lastRestart: '2026-08-27T10:15:00Z',
    uptimeSeconds: 11_702_400,
    environment: 'prod',
    owner: 'SRE',
    tags: ['storage', 'analytics'],
    health: {
      checkedAt: new Date().toISOString(),
      latencyMs: 7,
      errorRate: 0.0,
      availability: 99.99,
      status: 'healthy',
      dependencies: [],
    },
  },
  {
    id: 'speaches',
    name: 'Speaches STT/TTS',
    description: 'Local speech inference service for faster-distil-whisper transcription and TTS synthesis for voice agents.',
    version: '0.6.2',
    status: 'healthy',
    healthScore: 96,
    cpuUsage: 67,
    memoryUsage: 82,
    memoryBytes: 2_400_000_000,
    trafficBytesPerSec: 22_000_000,
    lastRestart: '2026-08-29T13:00:00Z',
    uptimeSeconds: 6_912_000,
    environment: 'prod',
    owner: 'Voice',
    tags: ['speech', 'stt', 'tts'],
    health: {
      checkedAt: new Date().toISOString(),
      latencyMs: 152,
      errorRate: 0.3,
      availability: 99.92,
      status: 'healthy',
      dependencies: [],
    },
  },
  {
    id: 'omniroute-ui',
    name: 'OmniRoute UI',
    description: 'Provider configuration dashboard and usage analytics for the OmniRoute gateway.',
    version: '1.7.1',
    status: 'healthy',
    healthScore: 93,
    cpuUsage: 9,
    memoryUsage: 32,
    memoryBytes: 340_000_000,
    trafficBytesPerSec: 4_000_000,
    lastRestart: '2026-08-30T08:00:00Z',
    uptimeSeconds: 1_296_000,
    environment: 'prod',
    owner: 'Platform',
    tags: ['ui', 'gateway'],
    health: {
      checkedAt: new Date().toISOString(),
      latencyMs: 22,
      errorRate: 0.2,
      availability: 99.92,
      status: 'healthy',
      dependencies: ['omniroute'],
    },
  },
  {
    id: 'sandbox-api',
    name: 'Sandbox API',
    description: 'Isolated runner API for executing candidate grading tasks in sandboxed environments.',
    version: '0.9.3',
    status: 'offline',
    healthScore: 0,
    cpuUsage: 0,
    memoryUsage: 0,
    memoryBytes: 0,
    trafficBytesPerSec: 0,
    lastRestart: '2026-08-28T05:12:00Z',
    uptimeSeconds: 0,
    environment: 'prod',
    owner: 'Automation',
    tags: ['sandbox', 'security'],
    health: {
      checkedAt: new Date().toISOString(),
      latencyMs: 0,
      errorRate: 0,
      availability: 0,
      status: 'offline',
      dependencies: [],
    },
  },
  {
    id: 'freepbx-web',
    name: 'FreePBX Web UI',
    description: 'Apache-hosted FreePBX GUI for inbound route mapping and PBX administration.',
    version: '16.0.26',
    status: 'warning',
    healthScore: 79,
    cpuUsage: 26,
    memoryUsage: 61,
    memoryBytes: 680_000_000,
    trafficBytesPerSec: 5_000_000,
    lastRestart: '2026-08-30T06:40:00Z',
    uptimeSeconds: 1_411_200,
    environment: 'prod',
    owner: 'PBX Ops',
    tags: ['pbx', 'gui'],
    health: {
      checkedAt: new Date().toISOString(),
      latencyMs: 98,
      errorRate: 2.3,
      availability: 99.41,
      status: 'warning',
      dependencies: ['freepbx'],
    },
  },
];

// Fallback/placeholder data shown only until the live API payload arrives (or
// while it's unreachable). Hosts must never be localhost or docker bridge IPs:
// derive the host from where this dashboard is actually served — the NPM
// subdomain when proxied (e.g. admin.capstone.innotel.us), otherwise the LAN
// IP the operator opened. Ports stay per-service because the fallback predates
// the live port map.
function fallbackHost(): string {
  if (typeof window === 'undefined') return 'localhost';
  return window.location.hostname;
}

const _fh = fallbackHost;

export const ports: Port[] = [
  { port: 8000, protocol: 'tcp', service: 'dograh-api', host: _fh(), status: 'open', environment: 'prod', owner: 'DevOps', risk: 'medium', lastSeen: '2026-08-31T16:42:00Z', utilization: 62, tags: ['voice-api'] },
  { port: 3010, protocol: 'tcp', service: 'dograh-ui', host: _fh(), status: 'open', environment: 'prod', owner: 'Frontend', risk: 'low', lastSeen: '2026-08-31T16:42:00Z', utilization: 38, tags: ['ui'] },
  { port: 3301, protocol: 'tcp', service: 'signoz', host: _fh(), status: 'open', environment: 'prod', owner: 'SRE', risk: 'medium', lastSeen: '2026-08-31T16:42:00Z', utilization: 71, tags: ['observability'] },
  { port: 8484, protocol: 'tcp', service: 'grist', host: _fh(), status: 'open', environment: 'prod', owner: 'Data', risk: 'low', lastSeen: '2026-08-31T16:42:00Z', utilization: 25, tags: ['data'] },
  { port: 5678, protocol: 'tcp', service: 'n8n', host: _fh(), status: 'open', environment: 'prod', owner: 'Automation', risk: 'low', lastSeen: '2026-08-31T16:42:00Z', utilization: 43, tags: ['automation'] },
  { port: 20128, protocol: 'tcp', service: 'omniroute', host: _fh(), status: 'open', environment: 'prod', owner: 'Platform', risk: 'medium', lastSeen: '2026-08-31T16:42:00Z', utilization: 68, tags: ['gateway'] },
  { port: 80, protocol: 'tcp', service: 'freepbx-web', host: _fh(), status: 'open', environment: 'prod', owner: 'PBX Ops', risk: 'medium', lastSeen: '2026-08-31T16:42:00Z', utilization: 54, tags: ['gui'] },
  { port: 3011, protocol: 'tcp', service: 'omniroute-ui', host: _fh(), status: 'open', environment: 'prod', owner: 'Platform', risk: 'low', lastSeen: '2026-08-31T16:42:00Z', utilization: 18, tags: ['ui'] },
  { port: 3001, protocol: 'tcp', service: 'speaches', host: _fh(), status: 'open', environment: 'prod', owner: 'Voice', risk: 'low', lastSeen: '2026-08-31T16:42:00Z', utilization: 76, tags: ['speech'] },
  { port: 9000, protocol: 'tcp', service: 'clickhouse', host: _fh(), status: 'open', environment: 'prod', owner: 'SRE', risk: 'medium', lastSeen: '2026-08-31T16:42:00Z', utilization: 82, tags: ['storage'] },
  { port: 5432, protocol: 'tcp', service: 'postgres', host: _fh(), status: 'open', environment: 'prod', owner: 'Platform', risk: 'high', lastSeen: '2026-08-31T16:42:00Z', utilization: 58, tags: ['database'] },
  { port: 6379, protocol: 'tcp', service: 'redis', host: _fh(), status: 'open', environment: 'prod', owner: 'Platform', risk: 'high', lastSeen: '2026-08-31T16:42:00Z', utilization: 41, tags: ['cache'] },
  { port: 8080, protocol: 'tcp', service: 'sandbox-api', host: _fh(), status: 'closed', environment: 'prod', owner: 'Automation', risk: 'medium', lastSeen: '2026-08-28T05:12:00Z', utilization: 0, tags: ['sandbox'] },
  { port: 3478, protocol: 'udp', service: 'coturn', host: '203.0.113.10', status: 'open', environment: 'prod', owner: 'Voice', risk: 'medium', lastSeen: '2026-08-31T16:41:00Z', utilization: 33, tags: ['turn', 'voip'] },
  { port: 5060, protocol: 'udp', service: 'freepbx', host: _fh(), status: 'open', environment: 'prod', owner: 'PBX Ops', risk: 'high', lastSeen: '2026-08-31T16:41:00Z', utilization: 91, tags: ['sip'] },
  { port: 10000, protocol: 'tcp', service: 'freepbx', host: _fh(), status: 'open', environment: 'prod', owner: 'PBX Ops', risk: 'medium', lastSeen: '2026-08-31T16:41:00Z', utilization: 12, tags: ['manager'] },
  { port: 443, protocol: 'tls', service: 'public-ingress', host: '203.0.113.10', status: 'open', environment: 'prod', owner: 'Platform', risk: 'medium', lastSeen: '2026-08-31T16:42:00Z', utilization: 74, tags: ['ingress'] },
  { port: 3022, protocol: 'tcp', service: 'dev-agent', host: _fh(), status: 'open', environment: 'dev', owner: 'DevOps', risk: 'low', lastSeen: '2026-08-31T16:40:00Z', utilization: 9, tags: ['dev'] },
  { port: 9100, protocol: 'tcp', service: 'node-exporter', host: _fh(), status: 'open', environment: 'prod', owner: 'SRE', risk: 'low', lastSeen: '2026-08-31T16:42:00Z', utilization: 4, tags: ['metrics'] },
  { port: 2112, protocol: 'udp', service: 'test-media', host: _fh(), status: 'filtered', environment: 'test', owner: 'Voice', risk: 'medium', lastSeen: '2026-08-30T14:05:00Z', utilization: 0, tags: ['media-test'] },
];

export const secrets: Secret[] = [
  { id: 's1', name: 'DOGRAH_ARI_PASSWORD', environment: 'prod', owner: 'DevOps', rotatedAt: '2026-07-02T00:00:00Z', expiresAt: '2026-08-31T00:00:00Z', status: 'active', permissions: [{ role: 'admin', grantedAt: '2026-05-01T00:00:00Z' }], type: 'password' },
  { id: 's2', name: 'OMNIROUTE_API_KEY', environment: 'prod', owner: 'Platform', rotatedAt: '2026-06-15T00:00:00Z', expiresAt: '2026-12-15T00:00:00Z', status: 'active', permissions: [{ role: 'operator', grantedAt: '2026-05-01T00:00:00Z' }], type: 'api-key' },
  { id: 's3', name: 'POSTGRES_PASSWORD', environment: 'prod', owner: 'Platform', rotatedAt: '2026-03-01T00:00:00Z', expiresAt: '2026-09-01T00:00:00Z', status: 'active', permissions: [{ role: 'admin', grantedAt: '2026-01-01T00:00:00Z' }], type: 'credential' },
  { id: 's4', name: 'Grist API Key', environment: 'prod', owner: 'Automation', rotatedAt: '2026-07-20T00:00:00Z', expiresAt: '2026-08-20T00:00:00Z', status: 'expired', permissions: [{ role: 'operator', grantedAt: '2026-05-01T00:00:00Z' }], type: 'api-key' },
  { id: 's5', name: 'Redis TLS Cert', environment: 'prod', owner: 'SRE', rotatedAt: '2026-08-01T00:00:00Z', expiresAt: '2026-11-01T00:00:00Z', status: 'active', permissions: [{ role: 'admin', grantedAt: '2026-06-01T00:00:00Z' }], type: 'certificate' },
  { id: 's6', name: 'Sandbox Runner Token', environment: 'prod', owner: 'Automation', rotatedAt: '2026-08-10T00:00:00Z', expiresAt: '2026-09-10T00:00:00Z', status: 'active', permissions: [{ role: 'operator', grantedAt: '2026-07-01T00:00:00Z' }], type: 'token' },
  { id: 's7', name: 'FreePBX AMI Secret', environment: 'prod', owner: 'PBX Ops', rotatedAt: '2026-04-10T00:00:00Z', expiresAt: '2026-08-10T00:00:00Z', status: 'expired', permissions: [{ role: 'admin', grantedAt: '2026-02-01T00:00:00Z' }], type: 'credential' },
  { id: 's8', name: 'Coturn Credentials', environment: 'prod', owner: 'Voice', rotatedAt: '2026-08-30T00:00:00Z', expiresAt: '2026-09-30T00:00:00Z', status: 'active', permissions: [{ role: 'operator', grantedAt: '2026-07-01T00:00:00Z' }], type: 'password' },
  { id: 's9', name: 'Stage OmniRoute Key', environment: 'stage', owner: 'Platform', rotatedAt: '2026-08-05T00:00:00Z', expiresAt: '2026-11-05T00:00:00Z', status: 'active', permissions: [{ role: 'viewer', grantedAt: '2026-08-05T00:00:00Z' }], type: 'api-key' },
  { id: 's10', name: 'Dev Service Account', environment: 'dev', owner: 'DevOps', rotatedAt: '2026-08-15T00:00:00Z', expiresAt: '2026-09-15T00:00:00Z', status: 'active', permissions: [{ role: 'operator', grantedAt: '2026-06-01T00:00:00Z' }], type: 'credential' },
  { id: 's11', name: 'Signoz JWT Secret', environment: 'prod', owner: 'SRE', rotatedAt: '2026-02-01T00:00:00Z', expiresAt: '2026-08-01T00:00:00Z', status: 'expired', permissions: [{ role: 'admin', grantedAt: '2026-01-01T00:00:00Z' }], type: 'token' },
  { id: 's12', name: 'N8N JWT Secret', environment: 'prod', owner: 'Automation', rotatedAt: '2026-08-20T00:00:00Z', expiresAt: '2026-10-20T00:00:00Z', status: 'active', permissions: [{ role: 'operator', grantedAt: '2026-08-20T00:00:00Z' }], type: 'token' },
];

export const alerts: Alert[] = [
  { id: 'a1', time: '2026-08-31T16:38:00Z', service: 'FreePBX Web UI', severity: 'warning', message: 'Response latency above threshold (98ms avg over 5 minutes)', status: 'open', assignedTo: 'PBX Ops', tags: ['latency', 'pbx'] },
  { id: 'a2', time: '2026-08-31T16:35:00Z', service: 'FreePBX Web UI', severity: 'warning', message: 'Error rate exceeded 2% in the last check window', status: 'acknowledged', assignedTo: 'PBX Ops', tags: ['errors', 'pbx'] },
  { id: 'a3', time: '2026-08-31T16:30:00Z', service: 'Sandbox API', severity: 'critical', message: 'Endpoint 8080 reporting closed; sandbox execution pipeline degraded', status: 'open', assignedTo: 'Automation', tags: ['sandbox', 'outage'] },
  { id: 'a4', time: '2026-08-31T16:22:00Z', service: 'Speaches STT/TTS', severity: 'warning', message: 'GPU memory pressure high; transcription queue latency rising', status: 'open', assignedTo: 'Voice', tags: ['gpu', 'speech'] },
  { id: 'a5', time: '2026-08-31T16:15:00Z', service: 'Dograh API', severity: 'info', message: 'Version 1.45.1 health check passed; no action required', status: 'resolved', assignedTo: '', tags: ['health'] },
  { id: 'a6', time: '2026-08-31T16:10:00Z', service: 'OmniRoute', severity: 'info', message: 'Cache hit rate dropped to 61%; current pool warm-up in progress', status: 'resolved', assignedTo: '', tags: ['cache', 'gateway'] },
  { id: 'a7', time: '2026-08-31T16:05:00Z', service: 'ClickHouse', severity: 'warning', message: 'Disk utilization above 80% on telemetry node', status: 'open', assignedTo: 'SRE', tags: ['storage', 'disk'] },
  { id: 'a8', time: '2026-08-31T15:58:00Z', service: 'Grist Interviews', severity: 'warning', message: 'Write throughput below baseline during candidate loop generation', status: 'acknowledged', assignedTo: 'Data', tags: ['write-throughput'] },
  { id: 'a9', time: '2026-08-31T15:50:00Z', service: 'Coturn', severity: 'info', message: 'TURN allocation count within expected range for current media sessions', status: 'resolved', assignedTo: '', tags: ['turn', 'capacity'] },
  { id: 'a10', time: '2026-08-31T15:42:00Z', service: 'Redis', severity: 'warning', message: 'Eviction rate elevated after memory policy change', status: 'open', assignedTo: 'Platform', tags: ['redis', 'memory'] },
  { id: 'a11', time: '2026-08-31T15:30:00Z', service: 'n8n Workflow', severity: 'critical', message: 'Grading webhook timeout on transcript fetch; one transcript stalled', status: 'escalated', assignedTo: 'Automation', tags: ['webhook', 'graders'] },
  { id: 'a12', time: '2026-08-31T15:20:00Z', service: 'FreePBX', severity: 'info', message: 'Route sync completed; 12 inbound routes mapped from dograh numbers', status: 'resolved', assignedTo: '', tags: ['routes', 'sync'] },
];

export const users: User[] = [
  { id: 'u1', name: 'Maya K.', email: 'maya@capstone.internal', role: 'admin', status: 'active', lastActive: '2026-08-31T16:42:00Z', createdAt: '2026-01-10T00:00:00Z', sessions: 142 },
  { id: 'u2', name: 'Daniel R.', email: 'daniel@capstone.internal', role: 'operator', status: 'active', lastActive: '2026-08-31T16:38:00Z', createdAt: '2026-02-05T00:00:00Z', sessions: 98 },
  { id: 'u3', name: 'Priya S.', email: 'priya@capstone.internal', role: 'operator', status: 'active', lastActive: '2026-08-31T16:20:00Z', createdAt: '2026-03-12T00:00:00Z', sessions: 87 },
  { id: 'u4', name: 'Tom W.', email: 'tom@capstone.internal', role: 'viewer', status: 'active', lastActive: '2026-08-31T15:50:00Z', createdAt: '2026-04-01T00:00:00Z', sessions: 41 },
  { id: 'u5', name: 'Alexei V.', email: 'alexei@capstone.internal', role: 'auditor', status: 'active', lastActive: '2026-08-31T15:30:00Z', createdAt: '2026-05-10T00:00:00Z', sessions: 12 },
  { id: 'u6', name: 'Conference Bot', email: 'bot@capstone.internal', role: 'viewer', status: 'disabled', lastActive: '2026-08-20T00:00:00Z', createdAt: '2026-06-01T00:00:00Z', sessions: 0 },
];

export const policies: ConfigPolicy[] = [
  { id: 'p1', name: 'Auto-restart on health failure', description: 'Attempt restart of non-critical services when health check fails twice', enabled: true, value: 'true', updatedAt: '2026-08-29T14:00:00Z' },
  { id: 'p2', name: 'Alert escalation timeout', description: 'Auto-escalate open critical alerts after this many minutes', enabled: true, value: '30', updatedAt: '2026-08-25T10:00:00Z' },
  { id: 'p3', name: 'Secrets rotation reminder', description: 'Warn owners N days before secret expiry', enabled: true, value: '30', updatedAt: '2026-08-15T12:00:00Z' },
  { id: 'p4', name: 'Environment access lockdown', description: 'Restrict prod access to admins and operators', enabled: true, value: 'admin|operator', updatedAt: '2026-07-01T00:00:00Z' },
  { id: 'p5', name: 'Audit log retention', description: 'Days to retain audit entries in hot storage', enabled: true, value: '90', updatedAt: '2026-06-20T00:00:00Z' },
];

export const auditLog: AuditEntry[] = [
  { id: 'au1', timestamp: '2026-08-31T16:40:00Z', actor: 'Maya K.', action: 'restart', resource: 'linux-freepbx', details: 'Service restarted via dashboard actions', ip: _fh() },
  { id: 'au2', timestamp: '2026-08-31T16:38:00Z', actor: 'Daniel R.', action: 'acknowledge', resource: 'alert/a2', details: 'Acknowledged FreePBX error rate alert', ip: _fh() },
  { id: 'au3', timestamp: '2026-08-31T16:35:00Z', actor: 'Priya S.', action: 'rotate', resource: 'secret/s8', details: 'Rotated Coturn credentials', ip: _fh() },
  { id: 'au4', timestamp: '2026-08-31T16:30:00Z', actor: 'system', action: 'scale', resource: 'signoz', details: 'Auto-scaled trace retention workers', ip: _fh() },
  { id: 'au5', timestamp: '2026-08-31T16:25:00Z', actor: 'Daniel R.', action: 'update_role', resource: 'user/u6', details: 'Disabled Conference Bot account', ip: _fh() },
  { id: 'au6', timestamp: '2026-08-31T16:20:00Z', actor: 'Maya K.', action: 'export', resource: 'ports', details: 'Exported port inventory CSV', ip: _fh() },
  { id: 'au7', timestamp: '2026-08-31T16:15:00Z', actor: 'Priya S.', action: 'config_change', resource: 'policy/p2', details: 'Updated alert escalation timeout to 30 minutes', ip: _fh() },
  { id: 'au8', timestamp: '2026-08-31T16:10:00Z', actor: 'Tom W.', action: 'view', resource: 'dashboard', details: 'Viewed dashboard overview', ip: _fh() },
  { id: 'au9', timestamp: '2026-08-31T16:05:00Z', actor: 'system', action: 'backup', resource: 'clickhouse', details: 'Daily telemetry backup snapshot completed', ip: _fh() },
  { id: 'au10', timestamp: '2026-08-31T16:00:00Z', actor: 'Maya K.', action: 'revoke', resource: 'api-key/old-omni', details: 'Revoked expired OmniRoute key', ip: _fh() },
  { id: 'au11', timestamp: '2026-08-31T15:55:00Z', actor: 'Daniel R.', action: 'acknowledge', resource: 'alert/a1', details: 'Acknowledged FreePBX latency alert', ip: _fh() },
  { id: 'au12', timestamp: '2026-08-31T15:45:00Z', actor: 'Priya S.', action: 'resolve', resource: 'alert/a6', details: 'Resolved OmniRoute cache alert', ip: _fh() },
];

export const healthData: HealthMatrixEntry[] = [
  { service: 'Dograh API', health: 98, availability: 99.97, latencyMs: 18, errorRate: 0.2, dependencies: ['postgres', 'redis'], lastCheck: '2026-08-31T16:42:00Z', status: 'healthy' },
  { service: 'Dograh UI', health: 96, availability: 99.95, latencyMs: 24, errorRate: 0.5, dependencies: ['dograh-api'], lastCheck: '2026-08-31T16:42:00Z', status: 'healthy' },
  { service: 'FreePBX', health: 82, availability: 99.89, latencyMs: 42, errorRate: 1.1, dependencies: ['dograh-api'], lastCheck: '2026-08-31T16:42:00Z', status: 'warning' },
  { service: 'OmniRoute', health: 99, availability: 99.99, latencyMs: 11, errorRate: 0.1, dependencies: [], lastCheck: '2026-08-31T16:42:00Z', status: 'healthy' },
  { service: 'n8n Workflow', health: 95, availability: 99.93, latencyMs: 31, errorRate: 0.3, dependencies: ['grist', 'dograh-api'], lastCheck: '2026-08-31T16:42:00Z', status: 'healthy' },
  { service: 'Grist Interviews', health: 97, availability: 99.98, latencyMs: 9, errorRate: 0.1, dependencies: [], lastCheck: '2026-08-31T16:42:00Z', status: 'healthy' },
  { service: 'SigNoz', health: 94, availability: 99.96, latencyMs: 36, errorRate: 0.2, dependencies: ['clickhouse'], lastCheck: '2026-08-31T16:42:00Z', status: 'healthy' },
  { service: 'ClickHouse', health: 97, availability: 99.99, latencyMs: 7, errorRate: 0.0, dependencies: [], lastCheck: '2026-08-31T16:42:00Z', status: 'healthy' },
  { service: 'Speaches STT/TTS', health: 96, availability: 99.92, latencyMs: 152, errorRate: 0.3, dependencies: [], lastCheck: '2026-08-31T16:42:00Z', status: 'healthy' },
  { service: 'OmniRoute UI', health: 93, availability: 99.92, latencyMs: 22, errorRate: 0.2, dependencies: ['omniroute'], lastCheck: '2026-08-31T16:42:00Z', status: 'healthy' },
  { service: 'Sandbox API', health: 0, availability: 0, latencyMs: 0, errorRate: 0, dependencies: [], lastCheck: '2026-08-31T16:42:00Z', status: 'offline' },
  { service: 'FreePBX Web UI', health: 79, availability: 99.41, latencyMs: 98, errorRate: 2.3, dependencies: ['freepbx'], lastCheck: '2026-08-31T16:42:00Z', status: 'warning' },
];

export const incidents: Incident[] = [
  { id: 'i1', time: '2026-08-30T14:20:00Z', title: 'FreePBX web UI latency spike after Apache restart', status: 'resolved', severity: 'warning', affected: ['freepbx-web'], resolvedAt: '2026-08-30T15:05:00Z' },
  { id: 'i2', time: '2026-08-30T09:10:00Z', title: 'Speaches model download finished; voice agents resumed', status: 'resolved', severity: 'info', affected: ['speaches', 'dograh-api'], resolvedAt: '2026-08-30T09:35:00Z' },
  { id: 'i3', time: '2026-08-29T18:00:00Z', title: 'ClickHouse compaction backlog raised disk utilization', status: 'resolved', severity: 'warning', affected: ['clickhouse'], resolvedAt: '2026-08-29T19:20:00Z' },
  { id: 'i4', time: '2026-08-28T05:10:00Z', title: 'Sandbox API container exited; grading pipeline degraded', status: 'open', severity: 'critical', affected: ['sandbox-api', 'n8n'] },
  { id: 'i5', time: '2026-08-27T12:00:00Z', title: 'OmniRoute provider failover exercised in stage', status: 'resolved', severity: 'info', affected: ['omniroute', 'omniroute-ui'], resolvedAt: '2026-08-27T12:40:00Z' },
];

export const links: ResourceLink[] = [
  { id: 'l1', name: 'Capstone Voice App', description: 'Agent workflow dashboard and telephony configuration', url: `http://${_fh()}:3010`, category: 'services', status: 'verified', lastVerified: '2026-08-31T16:42:00Z' },
  { id: 'l1a', name: 'Authentik', description: 'SSO and user management for the platform', url: `http://${_fh()}:9100`, category: 'services', status: 'verified', lastVerified: '2026-08-31T16:42:00Z' },
  { id: 'l1b', name: 'Capstone Control Center', description: 'Operational dashboard for the whole stack', url: `http://${_fh()}:8096`, category: 'services', status: 'verified', lastVerified: '2026-08-31T16:42:00Z' },
  { id: 'l2', name: 'FreePBX', description: 'PBX administration and inbound route mapping', url: `http://${_fh()}:80`, category: 'services', status: 'degraded', lastVerified: '2026-08-31T16:35:00Z' },
  { id: 'l3', name: 'OmniRoute', description: 'LLM gateway provider configuration and usage analytics', url: `http://${_fh()}:20128`, category: 'services', status: 'verified', lastVerified: '2026-08-31T16:40:00Z' },
  { id: 'l4', name: 'n8n', description: 'Workflow automation editor and execution logs', url: `http://${_fh()}:5678`, category: 'services', status: 'verified', lastVerified: '2026-08-31T16:42:00Z' },
  { id: 'l5', name: 'Grist', description: 'Interview records and candidate loop management', url: `http://${_fh()}:8484`, category: 'services', status: 'verified', lastVerified: '2026-08-31T16:42:00Z' },
  { id: 'l6', name: 'SigNoz', description: 'Distributed tracing, metrics, and logs dashboard', url: `http://${_fh()}:3301`, category: 'monitoring', status: 'verified', lastVerified: '2026-08-31T16:42:00Z' },
  { id: 'l7', name: 'Capstone Docs', description: 'Platform documentation and release notes', url: 'https://capstone.innotel.us', category: 'documentation', status: 'verified', lastVerified: '2026-08-30T00:00:00Z' },
  { id: 'l8', name: 'Capstone README', description: 'Project overview, release notes, and non-negotiables', url: 'https://capstone.innotel.us', category: 'documentation', status: 'verified', lastVerified: '2026-08-31T00:00:00Z' },
  { id: 'l9', name: 'OpenTelemetry Docs', description: 'OTel collector config patterns used in this stack', url: 'https://opentelemetry.io/docs/', category: 'documentation', status: 'verified', lastVerified: '2026-08-25T00:00:00Z' },
  { id: 'l10', name: 'SigNoz Dashboard', description: 'Service-level SLO and latency dashboards', url: `http://${_fh()}:3301/dashboards`, category: 'monitoring', status: 'verified', lastVerified: '2026-08-31T16:42:00Z' },
  { id: 'l11', name: 'Authentik Docs', description: 'Self-hosted identity provider documentation', url: 'https://docs.goauthentik.io/', category: 'documentation', status: 'verified', lastVerified: '2026-08-20T00:00:00Z' },
  { id: 'l12', name: 'Dograh Platform', description: 'Upstream dograh voice-agent platform used by this stack', url: 'https://github.com/dograh-hq/dograh', category: 'repositories', status: 'verified', lastVerified: '2026-08-20T00:00:00Z' },
  { id: 'l14', name: 'Asterisk Project', description: 'PBX core documentation for FreePBX and ARI', url: 'https://www.asterisk.org/', category: 'external', status: 'verified', lastVerified: '2026-08-20T00:00:00Z' },
  { id: 'l15', name: 'FreePBX Docs', description: 'FreePBX module and dialplan documentation', url: 'https://wiki.freepbx.org/', category: 'documentation', status: 'verified', lastVerified: '2026-08-20T00:00:00Z' },
  { id: 'l16', name: 'Internal Wiki', description: 'Ops runbooks, change logs, and contact roster', url: `http://${_fh()}:8081/wiki`, category: 'support', status: 'unknown', lastVerified: '2026-08-28T00:00:00Z' },
  { id: 'l17', name: 'Incident Channel', description: 'Team Slack channel for live incident coordination', url: `http://${_fh()}:8081/channels/incidents`, category: 'support', status: 'verified', lastVerified: '2026-08-31T16:00:00Z' },
  { id: 'l18', name: 'Vendor Escalation', description: 'External support escalation portal', url: 'https://support.example.com/capstone', category: 'support', status: 'verified', lastVerified: '2026-08-29T00:00:00Z' },
];

export const dashboardStats: DashboardStats = {
  totalServices: services.length,
  healthyServices: services.filter(s => s.status === 'healthy').length,
  warningServices: services.filter(s => s.status === 'warning').length,
  criticalServices: services.filter(s => s.status === 'critical').length,
  activePorts: ports.filter(p => p.status === 'open').length,
  openAlerts: alerts.filter(a => a.status === 'open').length,
  expiringSecrets: secrets.filter(s => new Date(s.expiresAt) < new Date(Date.now() + 7 * 24 * 60 * 60 * 1000)).length,
  uptimePercent: 99.93,
};
